/* ═══ v2.3.1943: A HEADBAND HAS TO FIT WHAT IS ON THE HEAD ═══
 *
 * Owner: "The K hat and the hairband don't work well with Afro."
 *
 * The three band-type hats are authored against a BARE HEAD, which the five
 * stand sheets draw 41-52px wide in the 256 frame.  Measured, each band is
 * 40-66px at the row it occupies, so it overhangs a bald skull by a few pixels
 * and reads as worn.  The afro is 60-74px at those same rows.  The same band on
 * it stops well inside the silhouette on both sides, and on the back views it
 * is a short bar across the middle of a smooth purple ball -- a sticker, not a
 * band.
 *
 * So a band is grown by exactly how much the hair swells the head, which puts
 * its overhang back where the art intended.  The numbers live in
 * hairSwell.json and are regenerated by tools/ui/measure-hair-swell.mjs.
 *
 * ── THE GROWTH IS HORIZONTAL ONLY, AND THAT WAS NOT THE FIRST ANSWER ──
 * Scaling uniformly is the obvious move and it is wrong, which the render made
 * obvious: at 1.49x the naruto headband came out half again as TALL as well as
 * wide, a black slab covering the whole forehead with its lower edge on the
 * eyes.  A real band round a bigger head of hair gets longer, not thicker.
 *
 * Horizontal-only also removes a whole problem rather than solving it.  Both
 * renderers scale a trait about its CROWN ANCHOR, which sits at the top of the
 * frame while a band sits up to 22px below it, so any vertical growth drags the
 * band down the face and has to be lifted back -- and the reference row for
 * that lift is awkward, because bandana-blue and bandana-2 have tails hanging
 * below the band and their bbox centre sits in the tails.  Growing in X only
 * moves nothing vertically, so none of that arithmetic exists.
 *
 * The cost is that the art stretches horizontally.  On a plain bar that is
 * invisible; the one piece with a detail in it is the naruto headband's plate,
 * and 1.5x is where that stops reading as a plate, which is what the cap below
 * is for.
 *
 * ── WHY ONLY THE AFRO, WHEN OTHER HAIR MEASURES NEARLY AS WIDE ──
 * This is a judgement the measurement cannot make, so it is written down rather
 * than hidden in a threshold.  `wavy` measures 1.31-1.44 against the afro's
 * 1.42-1.53, and a band on wavy already reads fine -- verified by rendering the
 * full hair x band grid.  What makes the afro different is not width alone but
 * that its silhouette is smooth and unbroken: a band that stops short of
 * TEXTURED hair reads as pressed into it, and the same band on a smooth ball
 * reads as pasted on.  Widening every hairstyle that measures wide would change
 * a pile of looks nobody complained about to fix the one that was reported.
 * The table holds every hairstyle so the next one can be judged the same way;
 * this set is the decision.
 */
import DATA from './hairSwell.json';
import { headwearIsBand } from './headwearCatalog.js';

const REFIT_HAIR = new Set(['afro']);

/* A band never needs to be more than half again its authored size -- past that
   the art stops reading as a band and starts reading as a hat.  The afro's
   measured swell tops out at 1.53, so this bites on exactly one facing. */
export const BAND_GROW_MAX = 1.5;
/* Below this the change would be invisible and not worth a second bake. */
const MIN_GROW = 1.05;

/** The horizontal scale multiplier for `hatId` on `hairId` facing `dir`, or 1
 *  when the refit does not apply.  A band grows by exactly the hair's swell, so
 *  its overhang over the hair matches the overhang the art was drawn with over
 *  a bare head. */
export function bandFit(hatId, hairId, dir) {
  if (!hatId || !hairId || hairId === 'none') return 1;
  if (!REFIT_HAIR.has(hairId) || !headwearIsBand(hatId)) return 1;
  const swell = DATA.hairSwell[hairId] && DATA.hairSwell[hairId][dir];
  if (!swell || swell < MIN_GROW) return 1;
  return Math.min(swell, BAND_GROW_MAX);
}
