#!/usr/bin/env python3
"""v2.3.2643: cut the picker tiles for the EYESTYLE slot — the eyes ON A FACE.

Why this is not the generic thumb
---------------------------------
import_headwear_green.py writes a thumb by cropping the piece's own art, which
is right for a hat (a hat is a recognisable object on its own) and hopeless for
a pair of eyes: the tiles it produced for these four were two navy slits, a
white blob, two flames and two white blocks, floating on transparency at a crop
so tight you cannot tell which way is up.  A player picking an eye style is
picking a FACE, so the tile has to show one.

Why it is not tools/ui/slice_eyewear_thumbs.py either
----------------------------------------------------
That tool cuts the EYEWEAR tiles out of a contact sheet the owner drew by hand,
and byte-compares them under --check so a re-run cannot silently overwrite art
he made (TRAPS 59).  There is no such sheet for eye styles, and there does not
need to be: the tile is derivable.  The piece's meta.json already says exactly
where it sits on the game's own head, so compositing it over the real stand
frame reproduces what the player will see, rather than approximating it.

It reuses preview_headwear.place(), which is itself a term-for-term mirror of
_placeTrait.  That is deliberate — a thumbnail generated by a second, private
copy of the placement maths would drift away from the renderer, and the tile
would stop matching the character (preview_headwear.py's own header makes the
same argument).

v2.3.2645: AND IT ERASES THE BASE EYE FIRST, the way the game does.  Owner:
"The 'one eye' thumbnail in the trait picker is a bit messed up."  It was: the
first cut composited the piece over the body sheet exactly as it ships, so the
character's own painted eyes were still under it.  The One Eye is a single
shape centred BETWEEN them, so neither of them was covered — their white ran out
either side of the piece and joined it into one wide band across the face, and
their dark top edges sat on it.  What the tile showed was a smear over the nose;
what the game shows is one eye, because the body bake paints the drawn-in eyes
out with sampled skin under a style (playerSkins._blankEyes, regions from
eyeBlankMask.json).  `blank_eyes` below is that step, and it is applied through
place(body_fx=...) so the placement maths stays in one file.

v2.3.2645: it also composites the 256px `hi/` art rather than the 128px shipped
frame, for the same reason characterPortrait does (v2.3.1579).  The tile is an
UPSCALE of a head that is 64 px wide in the body sheet, so feeding it the
downscaled art throws away the resolution the tile then tries to magnify: the
One Eye's pupil is 4 px at 256 and a grey smudge at 128.  Falls back to the
shipped frame if a piece has no hi/.

Run from the repo root:
    python3 tools/ui/make_eyestyle_thumbs.py                 # every id in the folder
    python3 tools/ui/make_eyestyle_thumbs.py --ids demon,wtf
    [--check]    compare against what is on disk and report, writing nothing
"""
import argparse
import importlib.util
import json
import os
import sys

import numpy as np
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TRAITS = os.path.join(REPO, 'public/sprites/traits/eyestyle')
TOPS = os.path.join(REPO, 'public/sprites/player/body-tops.json')
ANCHORS = os.path.join(REPO, 'public/sprites/player/body-anchors.json')
EYE_BLANK = os.path.join(REPO, 'src/rendering/eyeBlankMask.json')

_spec = importlib.util.spec_from_file_location(
    'preview_headwear', os.path.join(REPO, 'tools/preview_headwear.py'))
_pv = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_pv)

TILE = 128           # what the picker renders the tile at; the grid scales it down
PAD_X = 6            # 256-space px of skin kept either side of the head
PAD_TOP = 4
PAD_BOT = 2


def blank_eyes(im, boxes):
    """Paint the body's own eyes out with skin — the tile's copy of
    playerSkins._blankEyes, term for term.

    Same shape as the renderer's: sample the face in the two rings just outside
    each box (2 and 3 px out, never the 1 px ring, which is the eye's own
    anti-aliasing and fills a shade too dark), take a per-channel MEDIAN so one
    stray sample cannot drag the fill, and paint every non-transparent pixel of
    the box with it.  The colour is sampled rather than tabled for the reason
    the mask's own header gives: the player picks a skin tone at runtime and no
    table would stay in step with it.  Boxes come from eyeBlankMask.json, which
    is already in the 256-space these stand frames are in.
    """
    a = np.array(im).astype(int)
    h, w, _ = a.shape
    for bx, by, bw, bh in boxes:
        x0, x1 = bx, min(w, bx + bw)
        y0, y1 = by, min(h, by + bh)
        if x1 <= x0 or y1 <= y0:
            continue
        acc = []

        def vote(x, y):
            if 0 <= x < w and 0 <= y < h and a[y, x, 3] >= 200:
                acc.append(a[y, x, :3])

        for ring in (2, 3):
            for x in range(x0 - ring, x1 + ring):
                vote(x, y0 - ring)
                vote(x, y1 + ring - 1)
            for y in range(y0 - ring, y1 + ring):
                vote(x0 - ring, y)
                vote(x1 + ring - 1, y)
        if len(acc) < 8:                     # too little face round it to be sure
            continue
        fill = np.median(np.array(acc), axis=0).round().astype(int)
        box = a[y0:y1, x0:x1]
        box[box[:, :, 3] >= 40, :3] = fill   # never paint into transparency
    return Image.fromarray(a.astype(np.uint8))


def head_crop(d):
    """The 256-space rect of stand-<d> frame 0 holding the head, padded.

    body-anchors.json is the same reviewed table the mannequin sheet is built
    from, so the tile frames the head the same way every other head-trait tool
    in the repo does."""
    h = json.load(open(ANCHORS))[f'stand-{d}-0']['head']
    cx, w = h['center'][0], h['width']
    top, bot = h['top'][1], h['bottom'][1]
    half = w // 2 + PAD_X
    return (max(0, cx - half), max(0, top - PAD_TOP),
            min(_pv.FRAME, cx + half), min(_pv.FRAME, bot + PAD_BOT))


def tile_for(tid, d):
    """One composited tile, or None if the piece is not drawn on this facing."""
    folder = os.path.join(TRAITS, tid)
    meta = json.load(open(os.path.join(folder, 'meta.json')))
    if d not in meta.get('anchors', {}):
        return None
    art = {}
    for dd in _pv.DIRS:
        hi = os.path.join(folder, 'hi', f'{dd}.png')
        p = hi if os.path.exists(hi) else os.path.join(folder, f'{dd}.png')
        art[dd] = Image.open(p).convert('RGBA') if os.path.exists(p) else None
    tops = json.load(open(TOPS))
    boxes = json.load(open(EYE_BLANK)).get(f'stand-{d}', [[]])[0]
    cwd = os.getcwd()
    os.chdir(REPO)                      # place() reads the body sheets by relative path
    try:
        full = _pv.place(art, meta, tops, 'stand', d, 0, hid=tid,
                         body_fx=(lambda im: blank_eyes(im, boxes)) if boxes else None)
    finally:
        os.chdir(cwd)
    if full is None:
        return None
    x0, y0, x1, y1 = head_crop(d)
    crop = full.crop((x0, y0, x1, y1))
    # NEAREST, always: these are pixel tiles and any smoothing here shows up as
    # a grey halo round the eyes at the size the grid draws them.
    s = min(TILE / crop.width, TILE / crop.height)
    w2, h2 = max(1, round(crop.width * s)), max(1, round(crop.height * s))
    out = Image.new('RGBA', (TILE, TILE), (0, 0, 0, 0))
    out.paste(crop.resize((w2, h2), Image.NEAREST), ((TILE - w2) // 2, (TILE - h2) // 2))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ids', default=None, help='comma list; default every folder present')
    ap.add_argument('--check', action='store_true',
                    help='compare with what is on disk and report; write nothing')
    args = ap.parse_args()

    ids = ([x.strip() for x in args.ids.split(',') if x.strip()] if args.ids
           else sorted(d for d in os.listdir(TRAITS)
                       if os.path.isdir(os.path.join(TRAITS, d)) and d != 'hi'))
    if not ids:
        raise SystemExit(f'no eyestyle folders under {TRAITS}')

    differ = 0
    for tid in ids:
        for d, name in (('south', 'thumb.png'), ('southwest', 'thumb-sw.png')):
            im = tile_for(tid, d)
            if im is None:
                print(f'{tid:<10} {name:<14} skipped — the piece is not drawn on {d}')
                continue
            path = os.path.join(TRAITS, tid, name)
            if args.check:
                if not os.path.exists(path):
                    print(f'{tid:<10} {name:<14} MISSING on disk')
                    differ += 1
                    continue
                a = np.array(im)
                b = np.array(Image.open(path).convert('RGBA'))
                same = a.shape == b.shape and bool((a == b).all())
                print(f'{tid:<10} {name:<14} {"matches" if same else "DIFFERS from"} the file on disk')
                differ += 0 if same else 1
            else:
                im.save(path)
                print(f'{tid:<10} {name:<14} wrote {os.path.relpath(path, REPO)}')
    if args.check and differ:
        sys.exit(1)


if __name__ == '__main__':
    main()
