#!/usr/bin/env python3
"""v2.3.2825: the colour of the ground under your feet, per zone, baked offline.

Owner: "are there any footstep dust or dirt effect while moving? ... It would
need to match the color of the terrain though."

The dust existed (rendering/worldFx.js, v2.3.2703) with ONE colour per zone,
so a player walking off a sand path onto grass kicked up the same tan either
way.  The ground is a painted image, and the client never reads map pixels at
runtime (ambientFx.js's rule -- a GPU readback per step is exactly the iPhone
cost this game keeps avoiding), so this bakes the answer once:

  each zone's map -> GRID x GRID cells, each the cell's average colour (a
  median-ish trimmed mean, so one bright flower or dark stone does not
  decide a whole cell), stored as base64 RGB in src/data/groundColors.js.

At runtime groundColorAt(zone, x, y) is one array index.  Cells that are
WATER are written as 0,0,0 (a sentinel no real ground produces after the
lift below is not applied to it) and kick up no dust.

    python3 tools/maps/build_ground_colors.py
"""
import base64
import re
from PIL import Image, ImageFilter

GRID = 32
MAPS_JS = 'src/rendering/tiledMaps.js'
OUT = 'src/data/groundColors.js'


def zone_maps():
    src = open(MAPS_JS).read()
    block = src[src.index('export const IMAGE_ZONE_MAPS'):]
    block = block[:block.index('};')]
    return re.findall(r"^\s*(\w+):\s*'(/maps/[^']+\.webp)'", block, re.M)


def is_water(r, g, b):
    return b > r + 25 and b >= g - 5 and b > 70


def main():
    out = {}
    for zone, url in zone_maps():
        im = Image.open('public' + url).convert('RGB')
        # a light blur first so the cell mean is of the ground, not of the
        # single brightest pebble inside it
        im = im.filter(ImageFilter.BoxBlur(2))
        cw, ch = im.width / GRID, im.height / GRID
        px = im.load()
        buf = bytearray()
        for gy in range(GRID):
            for gx in range(GRID):
                x0, y0 = int(gx * cw), int(gy * ch)
                x1, y1 = max(x0 + 1, int((gx + 1) * cw)), max(y0 + 1, int((gy + 1) * ch))
                step = max(1, int(min(x1 - x0, y1 - y0) / 8))
                samples = [px[x, y] for y in range(y0, y1, step) for x in range(x0, x1, step)]
                # trimmed mean on luminance: drop the darkest and brightest
                # fifth (shadows under trees, flower highlights)
                samples.sort(key=lambda c: c[0] * 3 + c[1] * 6 + c[2])
                k = len(samples) // 5
                core = samples[k:len(samples) - k] or samples
                r = sum(c[0] for c in core) // len(core)
                g = sum(c[1] for c in core) // len(core)
                b = sum(c[2] for c in core) // len(core)
                if is_water(r, g, b):
                    buf += bytes((0, 0, 0))
                else:
                    buf += bytes((max(1, r), max(1, g), max(1, b)))
        out[zone] = base64.b64encode(bytes(buf)).decode()
        print(zone, url, len(out[zone]))

    lines = [
        '/* GENERATED by tools/maps/build_ground_colors.py -- do not edit by hand.',
        ' * v2.3.2825: each zone map averaged to a ' + str(GRID) + 'x' + str(GRID) + ' grid of RGB',
        ' * (base64), so footstep dust can take the colour of the ground it is',
        ' * kicked off without the client ever reading map pixels.  0,0,0 = water',
        ' * (no dust).  Re-run the tool when a zone map changes. */',
        'export const GROUND_GRID = ' + str(GRID) + ';',
        'export const GROUND_COLORS = {',
    ]
    for zone, b64 in out.items():
        lines.append('  ' + zone + ": '" + b64 + "',")
    lines.append('};')
    open(OUT, 'w').write('\n'.join(lines) + '\n')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
