/* AUTO-GENERATED by tools/build_attack_torso.mjs -- do not edit by hand.
 * Per-frame torso CUT row (skin->pants line) in the bow art frame, per facing.
 * The jog-legs composite lands the legs' waist on this row so top and bottom
 * meet at one clean skin->pants line every frame. */
export const BOW_TORSO_CUT = {
  "south": [
    142,
    142,
    142
  ],
  "southwest": [
    133,
    133,
    133
  ],
  "east": [
    147,
    147,
    147
  ],
  "north": [
    168,
    168,
    168
  ],
  "northwest": [
    155,
    156,
    155
  ]
};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function bowTorsoCutRow(dir, frameIdx) {
  const a = BOW_TORSO_CUT[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
