/* AUTO-GENERATED by tools/build_bow_waist.mjs -- do not edit by hand.
 * Per-frame torso CUT row (in the bow art frame) where the legs were erased,
 * per bow facing.  The jog-legs composite aligns the legs' waist to this row so
 * top and bottom meet exactly each frame. */
export const BOW_TORSO_CUT = {
  "south": [
    150,
    147,
    150
  ],
  "southwest": [
    137,
    137,
    137
  ],
  "east": [
    153,
    153,
    152
  ],
  "north": [
    174,
    174,
    174
  ],
  "northwest": [
    161,
    161,
    161
  ]
};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function bowTorsoCutRow(dir, frameIdx) {
  const a = BOW_TORSO_CUT[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
