/* AUTO-GENERATED by tools/build_jog_waist.mjs -- do not edit by hand.
 * v2.3.1656 exception: northeast's 24th entry (132) was hand-appended for the
 * restored frame 23, measured with the SAME detectWaist rule ported to the
 * 128px sheet (2x nearest upscale first).  The tool itself still assumes
 * 256px frames (stale since the v2.3.1434 128px re-cut), so a full regen
 * would silently corrupt every direction -- fix the tool before rerunning.
 * Per-frame waist (pants-top) row in the 256px jog body frame, per facing.
 * The bow-attack jog-legs composite crops the legs sprite at this row so the
 * lower torso never bleeds onto the legs as the run cycle bobs the body. */
export const JOG_WAIST = {
  "south": [
    133,
    133,
    134,
    138,
    139,
    141,
    142,
    143,
    143,
    143,
    141,
    141,
    132,
    132,
    131,
    132,
    138,
    139,
    141,
    142,
    143,
    143,
    143,
    142,
    135,
    134
  ],
  "east": [
    127,
    126,
    126,
    127,
    128,
    130,
    133,
    136,
    139,
    140,
    134,
    143,
    135,
    130,
    127,
    126,
    126,
    127,
    128,
    130,
    133,
    136,
    139,
    140,
    134,
    143,
    135,
    130
  ],
  "north": [
    132,
    132,
    132,
    132,
    132,
    131,
    130,
    130,
    130,
    130,
    131,
    131,
    131,
    131,
    132,
    131,
    131,
    129,
    130,
    130,
    130,
    131,
    131
  ],
  "northeast": [
    130,
    130,
    127,
    125,
    125,
    126,
    128,
    133,
    141,
    139,
    139,
    135,
    130,
    128,
    125,
    124,
    126,
    132,
    138,
    138,
    134,
    134,
    132,
    132
  ],
  "southwest": [
    128,
    131,
    138,
    142,
    131,
    129,
    130,
    130,
    139,
    141,
    129,
    124,
    130,
    137,
    136,
    129,
    127,
    136,
    142,
    137
  ]
};

/** Waist row for (dir, frameIdx); falls back to 138 if the sheet is unknown. */
export function jogWaistRow(dir, frameIdx) {
  const a = JOG_WAIST[dir];
  if (!a || !a.length) return 138;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
