/* AUTO-GENERATED by tools/build_attack_torso.mjs -- do not edit by hand.
 * Per-frame torso CUT row (skin->pants line) in the sword art frame, per facing.
 * The jog-legs composite lands the legs' waist on this row so top and bottom
 * meet at one clean skin->pants line every frame. */
export const SWORD_TORSO_CUT = {
  "south": [
    185,
    185,
    185,
    186,
    185,
    184,
    186,
    185,
    186,
    186,
    186,
    183,
    183,
    183
  ],
  "east": [
    133,
    107,
    119,
    137,
    136,
    125,
    129,
    126,
    124,
    119,
    118
  ],
  "north": [
    120,
    122,
    122,
    120,
    120,
    119,
    119,
    118,
    118
  ]
};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function swordTorsoCutRow(dir, frameIdx) {
  const a = SWORD_TORSO_CUT[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
