/* AUTO-GENERATED by tools/build_attack_torso.mjs -- do not edit by hand.
 * Per-frame torso CUT row (skin->pants line) in the sword art frame, per facing.
 * The jog-legs composite lands the legs' waist on this row so top and bottom
 * meet at one clean skin->pants line every frame. */
export const SWORD_TORSO_CUT = {
  "south": [
    186,
    186,
    186,
    186,
    187,
    200,
    188,
    187,
    187,
    187,
    187,
    186,
    186,
    186
  ],
  "east": [
    134,
    134,
    138,
    138,
    137,
    138,
    147,
    147,
    147,
    148,
    148
  ],
  "north": [
    123,
    124,
    123,
    122,
    121,
    120,
    120,
    119,
    119
  ]
};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function swordTorsoCutRow(dir, frameIdx) {
  const a = SWORD_TORSO_CUT[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
