/* Build leg-erased "torso" strips from the attack BODY sheets, so the renderer
   can draw animated jog-legs underneath while the upper body plays the attack.

   v2.3.1079: cut EXACTLY at the skin->pants colour change (the waist), per frame
   -- NOT a few px into the pants.  The jog-legs composite crops the legs at the
   SAME skin->pants line and lands them here, so the seam is one clean skin->pants
   transition (no bow-pants-meets-jog-pants double layer that read as misaligned).
   Also emits src/rendering/bowTorsoCut.js (the per-frame cut row) so the renderer
   aligns the legs to the actual baked cut.

   Run: node tools/build_attack_torso.mjs
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { decode, encode } from './png.mjs';

const SHEETS = [
  ['bow-south', 130, 234, 3], ['bow-southwest', 154, 233, 3], ['bow-east', 214, 241, 3],
  ['bow-north', 122, 260, 3], ['bow-northwest', 160, 248, 3],
];
// warm skin: clearly above blue, bright, R>=G>=B-ish (recolor-invariant boundary)
const isSkin = (r, g, b, a) => a > 140 && r > 150 && r - b > 35 && r >= g - 6 && g >= b - 6;

/* Waist = the skin->pants line: scan the central belly columns, take each
   column's lowest skin row, return the median + 1 (first non-skin row). */
function detectWaist(d, W, FW, FH, fi) {
  const x0 = Math.round(FW * 0.40), x1 = Math.round(FW * 0.60);
  const rows = [];
  for (let x = x0; x <= x1; x++) {
    let last = -1;
    for (let y = Math.round(FH * 0.30); y < FH; y++) { const i = (y * W + (fi * FW + x)) * 4; if (isSkin(d[i], d[i + 1], d[i + 2], d[i + 3])) last = y; }
    if (last > 0) rows.push(last + 1);
  }
  if (!rows.length) return Math.round(FH * 0.62);
  rows.sort((a, b) => a - b);
  return rows[Math.floor(rows.length / 2)];
}

const cutTable = {};
for (const [name, FW, FH, N] of SHEETS) {
  const im = decode(readFileSync(`public/sprites/player/${name}-body.png`));
  const { width: W, data: d } = im;
  const cuts = [];
  for (let fi = 0; fi < N; fi++) {
    const waist = detectWaist(d, W, FW, FH, fi);
    cuts.push(waist);
    for (let y = waist; y < FH; y++) for (let x = 0; x < FW; x++) { const i = (y * W + (fi * FW + x)) * 4; d[i] = d[i + 1] = d[i + 2] = d[i + 3] = 0; }
  }
  writeFileSync(`public/sprites/player/${name}-torso.png`, encode({ width: im.width, height: im.height, data: d }));
  cutTable[name.replace('bow-', '')] = cuts;
  console.log(`wrote ${name}-torso.png  cuts ${JSON.stringify(cuts)}`);
}

const body = `/* AUTO-GENERATED by tools/build_attack_torso.mjs -- do not edit by hand.
 * Per-frame torso CUT row (skin->pants line) in the bow art frame, per facing.
 * The jog-legs composite lands the legs' waist on this row so top and bottom
 * meet at one clean skin->pants line every frame. */
export const BOW_TORSO_CUT = ${JSON.stringify(cutTable, null, 2)};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function bowTorsoCutRow(dir, frameIdx) {
  const a = BOW_TORSO_CUT[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
`;
writeFileSync('src/rendering/bowTorsoCut.js', body);
console.log('wrote src/rendering/bowTorsoCut.js');
