/* Emit the per-frame waist CUT row of each bow torso strip -- the row where
 * build_attack_torso erased the legs (waist + OVERLAP).  The jog-legs composite
 * uses this as the exact meeting line so the legs' waist lands on the torso's
 * bottom edge every frame (no gap / no overlap), drawn at the torso's own scale.
 * Mirrors build_attack_torso's detection so the numbers match the actual cut.
 * Run: node tools/build_bow_waist.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { decode } from './png.mjs';

// [dir(cfg key), frameW, frameH, frames] -- same as build_attack_torso SHEETS
const SHEETS = [
  ['south', 130, 234, 3], ['southwest', 154, 233, 3], ['east', 214, 241, 3],
  ['north', 122, 260, 3], ['northwest', 160, 248, 3],
];
const OVERLAP = 6;   // must match build_attack_torso
const isPants = (r, g, b, a) => a > 80 && Math.abs(r - g) < 32 && g - b > 22 && r < 170 && b < 120;

const table = {};
for (const [name, FW, FH, N] of SHEETS) {
  const im = decode(readFileSync(`public/sprites/player/bow-${name}-body.png`));
  const { width: W, data: d } = im;
  const cuts = [];
  for (let fi = 0; fi < N; fi++) {
    let waist = -1;
    for (let y = Math.round(FH * 0.35); y < FH && waist < 0; y++) {
      let c = 0; for (let x = 0; x < FW; x++) { const i = (y * W + (fi * FW + x)) * 4; if (isPants(d[i], d[i + 1], d[i + 2], d[i + 3])) c++; }
      if (c > 3) waist = y;
    }
    if (waist < 0) waist = Math.round(FH * 0.62);
    cuts.push(waist + OVERLAP);
  }
  table[name] = cuts;
}

const body = `/* AUTO-GENERATED by tools/build_bow_waist.mjs -- do not edit by hand.
 * Per-frame torso CUT row (in the bow art frame) where the legs were erased,
 * per bow facing.  The jog-legs composite aligns the legs' waist to this row so
 * top and bottom meet exactly each frame. */
export const BOW_TORSO_CUT = ${JSON.stringify(table, null, 2)};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function bowTorsoCutRow(dir, frameIdx) {
  const a = BOW_TORSO_CUT[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
`;
writeFileSync('src/rendering/bowTorsoCut.js', body);
for (const k of Object.keys(table)) console.log(`${k}: cuts ${JSON.stringify(table[k])}`);
console.log('wrote src/rendering/bowTorsoCut.js');
