/* Detect the per-frame waist (pants-top) row on each base jog body sheet and
 * emit src/rendering/jogWaist.js -- a table the renderer uses to crop the
 * composited jog-legs sprite at the TRUE waist each frame (instead of a fixed
 * row), so the lower torso never bleeds onto the legs as the body bobs.
 * Geometry is recolor-invariant, so detecting on the base sheet is valid for
 * every recolored body.  Run: node tools/build_jog_waist.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { decode } from './png.mjs';

const DIRS = ['south', 'east', 'north', 'northeast', 'southwest'];
// olive pants in the base sheet: r~=g, clearly above blue, mid-dark
const isPants = (r, g, b, a) => a > 120 && Math.abs(r - g) < 22 && r - b > 22 && b < 95 && r > 45 && r < 150;

function detectWaist(im, fi) {
  const { width: W, data: d } = im;
  for (let y = 96; y < 210; y++) {
    let c = 0;
    for (let x = 0; x < 256; x++) { const i = (y * W + (fi * 256 + x)) * 4; if (isPants(d[i], d[i + 1], d[i + 2], d[i + 3])) c++; }
    if (c > 6) return y;
  }
  return 150;
}

const table = {};
for (const dir of DIRS) {
  const im = decode(readFileSync(`public/sprites/player/jog-${dir}.png`));
  const N = Math.round(im.width / 256);
  const arr = [];
  for (let fi = 0; fi < N; fi++) arr.push(detectWaist(im, fi));
  table[dir] = arr;
}

const body = `/* AUTO-GENERATED by tools/build_jog_waist.mjs -- do not edit by hand.
 * Per-frame waist (pants-top) row in the 256px jog body frame, per facing.
 * The bow-attack jog-legs composite crops the legs sprite at this row so the
 * lower torso never bleeds onto the legs as the run cycle bobs the body. */
export const JOG_WAIST = ${JSON.stringify(table, null, 2)};

/** Waist row for (dir, frameIdx); falls back to 138 if the sheet is unknown. */
export function jogWaistRow(dir, frameIdx) {
  const a = JOG_WAIST[dir];
  if (!a || !a.length) return 138;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
`;
writeFileSync('src/rendering/jogWaist.js', body);
for (const dir of DIRS) console.log(`${dir}: ${table[dir].length} frames, waist ${Math.min(...table[dir])}-${Math.max(...table[dir])}`);
console.log('wrote src/rendering/jogWaist.js');
