/* Detect the per-frame waist (pants-top) row on each base jog body sheet and
 * emit src/rendering/jogWaist.js -- a table the renderer uses to crop the
 * composited jog-legs sprite at the TRUE waist each frame (instead of a fixed
 * row), so the lower torso never bleeds onto the legs as the body bobs.
 * Geometry is recolor-invariant, so detecting on the base sheet is valid for
 * every recolored body.  Run: node tools/build_jog_waist.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { decode } from './png.mjs';

const DIRS = ['south', 'east', 'north', 'northeast', 'southwest'];
// warm skin: clearly above blue, bright (recolor-invariant skin->pants boundary).
// MUST match tools/build_attack_torso.mjs so the torso cut and the leg crop land
// on the same anatomical line.
const isSkin = (r, g, b, a) => a > 140 && r > 150 && r - b > 35 && r >= g - 6 && g >= b - 6;

/* Waist = the skin->pants line: central belly columns, median of each column's
   first non-skin row below the torso. */
function detectWaist(im, fi) {
  const { width: W, data: d } = im;
  const x0 = Math.round(256 * 0.40), x1 = Math.round(256 * 0.60);
  const rows = [];
  for (let x = x0; x <= x1; x++) {
    let last = -1;
    for (let y = 90; y < 215; y++) { const i = (y * W + (fi * 256 + x)) * 4; if (isSkin(d[i], d[i + 1], d[i + 2], d[i + 3])) last = y; }
    if (last > 0) rows.push(last + 1);
  }
  if (!rows.length) return 150;
  rows.sort((a, b) => a - b);
  return rows[Math.floor(rows.length / 2)];
}

const table = {};
for (const dir of DIRS) {
  const im = decode(readFileSync(`public/sprites/player/jog-${dir}.png`));
  const N = Math.round(im.width / 256);
  const arr = [];
  for (let fi = 0; fi < N; fi++) arr.push(detectWaist(im, fi));
  table[dir] = arr;
}

const body = `/* AUTO-GENERATED by tools/build_jog_waist.mjs -- do not edit by hand.
 * Per-frame waist (pants-top) row in the 256px jog body frame, per facing.
 * The bow-attack jog-legs composite crops the legs sprite at this row so the
 * lower torso never bleeds onto the legs as the run cycle bobs the body. */
export const JOG_WAIST = ${JSON.stringify(table, null, 2)};

/** Waist row for (dir, frameIdx); falls back to 138 if the sheet is unknown. */
export function jogWaistRow(dir, frameIdx) {
  const a = JOG_WAIST[dir];
  if (!a || !a.length) return 138;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
`;
writeFileSync('src/rendering/jogWaist.js', body);
for (const dir of DIRS) console.log(`${dir}: ${table[dir].length} frames, waist ${Math.min(...table[dir])}-${Math.max(...table[dir])}`);
console.log('wrote src/rendering/jogWaist.js');
