/* Build leg-erased "torso" strips from the attack BODY sheets, so the renderer
   can draw animated jog-legs underneath while the upper body plays the attack.

   v2.3.1079: cut EXACTLY at the skin->pants colour change (the waist), per frame.
   The jog-legs composite crops the legs at the SAME skin->pants line and lands
   them on the emitted cut row, so the seam is one clean transition.
   v2.3.1088: also handle the SWORD sheets -> sword-<dir>-torso.png +
   src/rendering/swordTorsoCut.js (same pipeline as the bow).

   Run: node tools/build_attack_torso.mjs
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { decode, encode } from './png.mjs';

const GROUPS = [
  {
    prefix: 'bow', out: 'src/rendering/bowTorsoCut.js', exp: 'BOW_TORSO_CUT', fn: 'bowTorsoCutRow',
    sheets: [
      ['bow-south', 130, 234, 3], ['bow-southwest', 154, 233, 3], ['bow-east', 214, 241, 3],
      ['bow-north', 122, 260, 3], ['bow-northwest', 160, 248, 3],
    ],
  },
  {
    prefix: 'sword', out: 'src/rendering/swordTorsoCut.js', exp: 'SWORD_TORSO_CUT', fn: 'swordTorsoCutRow',
    sheets: [
      ['sword-south', 320, 320, 14], ['sword-east', 402, 246, 11], ['sword-north', 340, 227, 9],
    ],
  },
];
/* warm skin INCLUDING darker tan/orange shading (muscle lines, shadows) on the
   bare torso -- the real torso<->pants boundary is the BLACK OUTLINE above the
   olive pants, NOT a darker tan/orange body line.  v2.3.1098: dropped the old
   `r>150` brightness floor (it stopped at shaded lower abs -> the waist was
   detected at a muscle line and the shirtless east torso got chopped).  Keep it
   recolor-invariant: warm = r clearly above g (excludes olive pants, where
   g>=r) and well above b (excludes the near-grey/black outline). */
const isSkin = (r, g, b, a) => a > 120 && (r - g) > 15 && (r - b) > 28 && g >= b - 8;
/* olive pants: r ~= g (low warm separation), g clearly above b, mid/low bright.
   Used to confirm a skin row is the TRUE torso->pants boundary. */
const isPants = (r, g, b, a) => a > 150 && Math.abs(r - g) < 18 && (g - b) > 12 && r < 165 && g < 165;

/* Waist = the torso->pants line.  v2.3.1098: a column's lowest skin row only
   counts if OLIVE PANTS sit just below it (across the black outline).  This
   ignores (a) the torso's front edge / sword arm, which on a profile (east)
   swing ends in mid-air well ABOVE the waist and used to drag the median up and
   chop the shirtless torso, and (b) darker tan/orange body lines mid-torso.
   Only the black-outline-above-pants boundary is the real waist. */
function detectWaist(d, W, FW, FH, fi) {
  const x0 = Math.round(FW * 0.38), x1 = Math.round(FW * 0.62);
  const rows = [];
  for (let x = x0; x <= x1; x++) {
    let waist = -1;
    for (let y = Math.round(FH * 0.30); y < FH; y++) {
      const i = (y * W + (fi * FW + x)) * 4;
      if (!isSkin(d[i], d[i + 1], d[i + 2], d[i + 3])) continue;
      /* require olive pants within ~9px below (the black outline sits between),
         so body edges / arms that fade to transparency don't qualify. */
      let pantsBelow = false;
      for (let yy = y + 1; yy <= Math.min(FH - 1, y + 9); yy++) {
        const j = (yy * W + (fi * FW + x)) * 4;
        if (isPants(d[j], d[j + 1], d[j + 2], d[j + 3])) { pantsBelow = true; break; }
      }
      if (pantsBelow) waist = y + 1;   // lowest skin row that truly meets pants
    }
    if (waist > 0) rows.push(waist);
  }
  if (!rows.length) return Math.round(FH * 0.62);
  rows.sort((a, b) => a - b);
  return rows[Math.floor(rows.length / 2)];
}

for (const grp of GROUPS) {
  const cutTable = {};
  for (const [name, FW, FH, N] of grp.sheets) {
    const im = decode(readFileSync(`public/sprites/player/${name}-body.png`));
    const { width: W, data: d } = im;
    const cuts = [];
    for (let fi = 0; fi < N; fi++) {
      const waist = detectWaist(d, W, FW, FH, fi);
      cuts.push(waist);
      for (let y = waist; y < FH; y++) for (let x = 0; x < FW; x++) { const i = (y * W + (fi * FW + x)) * 4; d[i] = d[i + 1] = d[i + 2] = d[i + 3] = 0; }
    }
    writeFileSync(`public/sprites/player/${name}-torso.png`, encode({ width: im.width, height: im.height, data: d }));
    cutTable[name.replace(grp.prefix + '-', '')] = cuts;
    console.log(`wrote ${name}-torso.png  cuts ${JSON.stringify(cuts)}`);
  }
  const body = `/* AUTO-GENERATED by tools/build_attack_torso.mjs -- do not edit by hand.
 * Per-frame torso CUT row (skin->pants line) in the ${grp.prefix} art frame, per facing.
 * The jog-legs composite lands the legs' waist on this row so top and bottom
 * meet at one clean skin->pants line every frame. */
export const ${grp.exp} = ${JSON.stringify(cutTable, null, 2)};

/** Torso cut row for (dir, frameIdx); falls back to a mid-frame estimate. */
export function ${grp.fn}(dir, frameIdx) {
  const a = ${grp.exp}[dir];
  if (!a || !a.length) return 150;
  return a[((frameIdx % a.length) + a.length) % a.length];
}
`;
  writeFileSync(grp.out, body);
  console.log(`wrote ${grp.out}`);
}
