/* Build the layered SHIRT bow-shot strips from the owner's hand-drawn grids.

   Mirrors tools/build_shirt_swing.mjs (the south sword-swing) but generalised
   per BOW facing.  The owner drew FULL characters (cyan shirt + orange skin +
   olive pants + grey grid).  The shirt is a distinct CYAN hue, so we isolate it
   by hue (drop skin/pants/bg), keep the shirt's own outline (dark pixels touching
   the cyan), despeckle to the largest blob, recolour to a white-base grayscale
   (transparent bg) so the renderer tints it at runtime, then align each shirt
   frame onto the matching bow BODY frame (public/sprites/player/bow-<dir>-body.png)
   so collar->neck and hem->waist land by construction, width fitted to the torso.

   Output: public/sprites/gear/shirt/tshirt/bowshot-<dir>.png, geometry matched to
   the body sheet (per-direction fw x fh, 3 frames).  west/southeast/northeast are
   mirror-generated by the renderer, so only east/southwest/south/northwest/north
   are authored here.  The NE drawing is flipped to author NORTHWEST.

   Run:
     node tools/build_shirt_bow.mjs <dir>            # write one direction's strip
     node tools/build_shirt_bow.mjs <dir> --preview  # also write an overlay board
     node tools/build_shirt_bow.mjs all              # all five
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { decode, encode } from './png.mjs';

const GEAR_DIR = 'public/sprites/gear/shirt/tshirt';

/* Per-direction config.  src = owner grid; (cols,rows,row) locate the cells for
   this facing within the grid; flipX mirrors the source (NE art -> NW sheet).
   body = the bare bow body the shirt aligns onto; fw/fh/n = its frame geometry. */
const DIRS = {
  south: {
    src: 'tools/bowshirt_src/south.png', cols: 3, rows: 1, row: 0, flipX: false,
    body: 'public/sprites/player/bow-south-body.png', fw: 130, fh: 234, n: 3,
  },
  southwest: {
    src: 'tools/bowshirt_src/southwest.png', cols: 3, rows: 1, row: 0, flipX: false,
    body: 'public/sprites/player/bow-southwest-body.png', fw: 154, fh: 233, n: 3,
  },
  east: {
    src: 'tools/bowshirt_src/grid_north_ne_east.png', cols: 3, rows: 3, row: 2, flipX: false,
    body: 'public/sprites/player/bow-east-body.png', fw: 214, fh: 241, n: 3,
  },
  north: {
    src: 'tools/bowshirt_src/grid_north_ne_east.png', cols: 3, rows: 3, row: 0, flipX: false,
    body: 'public/sprites/player/bow-north-body.png', fw: 122, fh: 260, n: 3,
  },
  northwest: {
    /* owner drew NORTHEAST (grid row 1); flip horizontally to author NW. */
    src: 'tools/bowshirt_src/grid_north_ne_east.png', cols: 3, rows: 3, row: 1, flipX: true,
    body: 'public/sprites/player/bow-northwest-body.png', fw: 160, fh: 248, n: 3,
  },
};

/* ── tone shaping (match stand/jog/swing shirt sheets) ──────────────────────── */
const FILL_TARGET = 245;
const OUTLINE_GAMMA = 1.5;
const TORSO_FILL = 1.15;   // shirt width = median hip width x this (shoulders read a touch wider than the hips)
const NECK_FROM_CROWN = 30; // collar sits this far below the head crown (bow heads sit lower than swing)
const BAND_FRAC = 0.30;

/* ── source-cell shirt isolation ────────────────────────────────────────────── */
function cellShirt(g, cfg, idx) {
  const GW = g.width, GH = g.height;
  const cpw = GW / cfg.cols, cph = GH / cfg.rows;
  const col = idx, row = cfg.row;
  const ox = Math.round(col * cpw), oy = Math.round(row * cph);
  const W = Math.round(cpw), H = Math.round(cph);
  const gpx = (x, y) => { const i = ((oy + y) * GW + (ox + x)) * 4; return [g.data[i], g.data[i + 1], g.data[i + 2], g.data[i + 3]]; };
  const MARGIN = Math.round(Math.min(W, H) * 0.04); // skip cell dividers

  const cyan = new Uint8Array(W * H);   // shirt fill
  const dark = new Uint8Array(W * H);   // candidate outline
  const bright = new Float32Array(W * H);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (x < MARGIN || x >= W - MARGIN || y < MARGIN || y >= H - MARGIN) continue;
    const [r, gg, b, a] = gpx(x, y);
    if (a < 40) continue;
    const isCyan = b > r + 18 && gg > r + 6;          // cyan/teal shirt fill
    const isDark = Math.max(r, gg, b) < 110;           // any dark outline
    if (isCyan) { cyan[y * W + x] = 1; bright[y * W + x] = Math.max(gg, b); }
    else if (isDark) { dark[y * W + x] = 1; bright[y * W + x] = Math.max(r, gg, b); }
  }
  /* Keep dark outline pixels only within ~2px of a cyan pixel (the shirt's own
     edge), dropping the body/pants/arm outlines AND the drawn bowstring, which
     runs a few px off the shirt.  Tight radius = shirt edge only. */
  const R = 2;
  const alp = new Uint8Array(W * H);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (cyan[y * W + x]) { alp[y * W + x] = 1; continue; }
    if (!dark[y * W + x]) continue;
    let near = false;
    for (let dy = -R; dy <= R && !near; dy++) for (let dx = -R; dx <= R; dx++) {
      const xx = x + dx, yy = y + dy;
      if (xx >= 0 && yy >= 0 && xx < W && yy < H && cyan[yy * W + xx]) { near = true; break; }
    }
    if (near) alp[y * W + x] = 1;
  }
  /* Despeckle: keep every sizable cyan component, not just the single largest.
     In some poses a drawn arm/bow crosses the shirt and SPLITS it into two
     blobs; keeping only the biggest would drop half the shirt and wreck the
     vertical scale.  Drop only small specks (< 12% of the largest, and a hard
     floor) so motion droplets / AA fuzz go but both shirt halves stay. */
  const lab = new Int32Array(W * H).fill(-1);
  const sizes = [];
  const stack = [];
  let compId = 0;
  for (let i = 0; i < W * H; i++) {
    if (!alp[i] || lab[i] >= 0) continue;
    const id = compId++; let n = 0; lab[i] = id; stack.push(i);
    while (stack.length) {
      const p = stack.pop(); const px = p % W, py = (p / W) | 0; n++;
      const nb = [];
      if (px > 0) nb.push(p - 1); if (px < W - 1) nb.push(p + 1);
      if (py > 0) nb.push(p - W); if (py < H - 1) nb.push(p + W);
      for (const q of nb) if (alp[q] && lab[q] < 0) { lab[q] = id; stack.push(q); }
    }
    sizes[id] = n;
  }
  const bestN = sizes.reduce((m, n) => Math.max(m, n || 0), 0);
  const keepMin = Math.max(40, Math.round(0.12 * bestN));
  for (let i = 0; i < W * H; i++) if (alp[i] && (sizes[lab[i]] || 0) < keepMin) alp[i] = 0;

  /* optional horizontal flip (NE art -> NW sheet). */
  if (cfg.flipX) {
    const a2 = new Uint8Array(W * H), b2 = new Float32Array(W * H);
    for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
      a2[y * W + (W - 1 - x)] = alp[y * W + x];
      b2[y * W + (W - 1 - x)] = bright[y * W + x];
    }
    alp.set(a2); bright.set(b2);
  }

  /* landmarks: torso band (collar -> hem) + collar centroid. */
  let maxV = 1;
  for (let i = 0; i < W * H; i++) if (alp[i] && bright[i] > maxV) maxV = bright[i];
  const rowW = new Int32Array(H);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (alp[y * W + x]) rowW[y]++;
  let maxW = 0; for (let y = 0; y < H; y++) if (rowW[y] > maxW) maxW = rowW[y];
  const thr = Math.max(3, Math.round(BAND_FRAC * maxW));
  let sTop = -1, sBot = -1, fTop = -1, fBot = -1;
  for (let y = 0; y < H; y++) {
    if (rowW[y] > 0) { if (fTop < 0) fTop = y; fBot = y; }
    if (rowW[y] >= thr) { if (sTop < 0) sTop = y; sBot = y; }
  }
  if (sTop < 0) { sTop = fTop; sBot = fBot; }
  const collarBot = sTop + Math.max(2, Math.round(0.25 * (sBot - sTop)));
  let colSum = 0, colN = 0;
  for (let y = sTop; y <= collarBot; y++) for (let x = 0; x < W; x++) if (alp[y * W + x]) { colSum += x; colN++; }
  const collarX = colN ? colSum / colN : W / 2;

  /* white-base grayscale */
  const val = new Float32Array(W * H);
  for (let i = 0; i < W * H; i++) if (alp[i]) val[i] = Math.round(FILL_TARGET * Math.pow(Math.min(1, bright[i] / maxV), OUTLINE_GAMMA));
  return { W, H, alp, val, collarX, sTop, sBot, fTop, fBot, torsoW: maxW };
}

/* ── body landmarks per frame ───────────────────────────────────────────────── */
function bodyLandmarks(body, cfg, fi) {
  const { fw: FW, fh: FH } = cfg; const BW = body.width;
  const isSkin = (r, g, b, a) => a > 80 && r - g > 40 && g - b > 15 && r > 140;
  const isPants = (r, g, b, a) => a > 80 && Math.abs(r - g) < 32 && g - b > 22 && r < 170 && b < 120;
  let crown = -1, waist = -1;
  for (let y = 0; y < FH && crown < 0; y++) {
    let c = 0; for (let x = 0; x < FW; x++) { const i = (y * BW + (fi * FW + x)) * 4; if (isSkin(body.data[i], body.data[i + 1], body.data[i + 2], body.data[i + 3])) c++; }
    if (c > 2) crown = y;
  }
  for (let y = (crown < 0 ? 0 : crown) + 20; y < FH && waist < 0; y++) {
    let c = 0; for (let x = 0; x < FW; x++) { const i = (y * BW + (fi * FW + x)) * 4; if (isPants(body.data[i], body.data[i + 1], body.data[i + 2], body.data[i + 3])) c++; }
    if (c > 3) waist = y;
  }
  if (crown < 0) crown = Math.round(FH * 0.17);
  const neckY = crown + NECK_FROM_CROWN;
  if (waist < 0 || waist <= neckY) waist = neckY + Math.round(FH * 0.28);
  /* width reference = the PANTS (hip) bbox just below the waist.  This is
     arm-free and rock-stable across the draw cycle (verified: south = 47px,
     center 65 on all 3 frames), unlike the neck->waist torso band which the
     extended bow-arms inflate and destabilise (collapsing the shirt to a sliver
     on the full-draw frame).  renderDir() fixes ONE width per direction from the
     median of these so the shirt can't jump frame-to-frame; the per-frame hip
     center still lets it track any lean. */
  let hminx = FW, hmaxx = -1;
  const hbTop = waist + 2, hbBot = Math.min(FH - 1, waist + 18);
  for (let y = hbTop; y <= hbBot; y++) for (let x = 0; x < FW; x++) {
    const i = (y * BW + (fi * FW + x)) * 4;
    if (isPants(body.data[i], body.data[i + 1], body.data[i + 2], body.data[i + 3])) { if (x < hminx) hminx = x; if (x > hmaxx) hmaxx = x; }
  }
  const hipW = hmaxx >= hminx ? (hmaxx - hminx) : Math.round(FW * 0.36);
  const hipCx = hmaxx >= hminx ? (hminx + hmaxx) / 2 : FW / 2;
  return { neckY, waistY: waist, hipCx, hipW };
}

/* bilinear sample */
function sample(buf, lx, ly) {
  const { W, H, val, alp } = buf;
  const x0 = Math.floor(lx), y0 = Math.floor(ly), fx = lx - x0, fy = ly - y0;
  let v = 0, a = 0, ws = 0;
  for (let dy = 0; dy <= 1; dy++) for (let dx = 0; dx <= 1; dx++) {
    const xx = x0 + dx, yy = y0 + dy; if (xx < 0 || yy < 0 || xx >= W || yy >= H) continue;
    const w = (dx ? fx : 1 - fx) * (dy ? fy : 1 - fy); const i = yy * W + xx;
    a += w * alp[i] * 255; if (alp[i]) { v += w * val[i]; ws += w; }
  }
  return [ws > 0 ? v / ws : 0, a];
}

function renderDir(dir, opts = {}) {
  const cfg = DIRS[dir]; if (!cfg) throw new Error('unknown dir ' + dir);
  const g = decode(readFileSync(cfg.src));
  const body = decode(readFileSync(cfg.body));
  const { fw: FW, fh: FH, n: N } = cfg;
  /* pass 1: landmarks for every frame -> ONE constant shirt width for the whole
     direction (median hip width x fill, so shoulders read a touch wider than the
     hips).  This is what kills the frame-to-frame width jump. */
  const Ls = []; for (let fi = 0; fi < N; fi++) Ls.push(bodyLandmarks(body, cfg, fi));
  const med = (arr) => { const s = [...arr].sort((a, b) => a - b); return s[s.length >> 1]; };
  const widthTarget = med(Ls.map((L) => L.hipW)) * TORSO_FILL;
  const frames = [];
  const dbg = [];
  for (let fi = 0; fi < N; fi++) {
    const s = cellShirt(g, cfg, fi);
    const L = Ls[fi];
    const SY = (L.waistY - L.neckY) / Math.max(1, (s.fBot - s.fTop));
    const SX = widthTarget / Math.max(1, s.torsoW);   // output width == widthTarget for every frame
    const out = Buffer.alloc(FW * FH * 4);
    for (let fy = 0; fy < FH; fy++) for (let fx = 0; fx < FW; fx++) {
      const lx = (fx - L.hipCx) / SX + s.collarX;
      const ly = (fy - L.neckY) / SY + s.fTop;
      const [v, a] = sample(s, lx, ly);
      if (a <= 4) continue;
      const o = (fy * FW + fx) * 4; const vv = Math.round(v);
      out[o] = vv; out[o + 1] = vv; out[o + 2] = vv; out[o + 3] = Math.round(a);
    }
    frames.push(out);
    dbg.push({ fi, neckY: L.neckY, waistY: L.waistY, hipCx: Math.round(L.hipCx), hipW: L.hipW, wTarget: Math.round(widthTarget), SX: SX.toFixed(2), SY: SY.toFixed(2) });
  }
  // assemble strip
  const SW = N * FW;
  const strip = Buffer.alloc(SW * FH * 4);
  for (let i = 0; i < N; i++) for (let y = 0; y < FH; y++) for (let x = 0; x < FW; x++) {
    const sI = (y * FW + x) * 4, d = (y * SW + (i * FW + x)) * 4;
    strip[d] = frames[i][sI]; strip[d + 1] = frames[i][sI + 1]; strip[d + 2] = frames[i][sI + 2]; strip[d + 3] = frames[i][sI + 3];
  }
  const OUT = `${GEAR_DIR}/bowshot-${dir}.png`;
  writeFileSync(OUT, encode({ width: SW, height: FH, data: strip }));
  console.log('wrote', OUT, SW + 'x' + FH, `(${N} frames)`);
  console.table(dbg);

  if (opts.preview) {
    const BW = N * FW;
    const board = Buffer.alloc(BW * FH * 4);
    for (let fi = 0; fi < N; fi++) for (let y = 0; y < FH; y++) for (let x = 0; x < FW; x++) {
      const bsrc = (y * body.width + (fi * FW + x)) * 4;
      let r = 40, gg = 44, b = 52;
      if (body.data[bsrc + 3] > 20) { const bl = Math.round(0.3 * body.data[bsrc] + 0.59 * body.data[bsrc + 1] + 0.11 * body.data[bsrc + 2]); r = gg = b = Math.round(60 + bl * 0.5); }
      const fs = (y * FW + x) * 4; const f = frames[fi];
      if (f[fs + 3] > 20) { const t = f[fs] / 255, al = f[fs + 3] / 255; r = Math.round(r * (1 - al) + (60 * t + 20) * al); gg = Math.round(gg * (1 - al) + (120 * t + 20) * al); b = Math.round(b * (1 - al) + (220 * t + 35) * al); }
      const d = (y * BW + (fi * FW + x)) * 4; board[d] = r; board[d + 1] = gg; board[d + 2] = b; board[d + 3] = 255;
    }
    const PV = `tools/_bowshirt_${dir}_preview.png`;
    writeFileSync(PV, encode({ width: BW, height: FH, data: board }));
    console.log('preview ->', PV);
  }
}

const arg = process.argv[2];
const preview = process.argv.includes('--preview');
if (!arg) { console.error('usage: node tools/build_shirt_bow.mjs <dir|all> [--preview]'); process.exit(1); }
if (arg === 'all') { for (const d of Object.keys(DIRS)) renderDir(d, { preview }); }
else renderDir(arg, { preview });
