#!/usr/bin/env python3
"""v2.3.1532: rebuild a hat's hair-clip mask from the hat it actually is now.

v2.3.1957: part 1 bounds the hair's WIDTH to the hat's -- the owner's rule, see
"The mask" below -- and bald_px is re-aimed to match it.

What a hairmask is for
----------------------
When a hat declares `clipsHair`, the renderer masks the hair sprite to the
hat's downward-filled silhouette, so long hair cannot poke out of the top or
the sides of a helmet while the forehead hair under its brim still shows
(_clipHairToHat, entityRenderer). The mask is placed by the SAME _placeTrait
call as the hat, with the hat's own meta, so it lands exactly over it.

Why they had to be rebuilt
--------------------------
Thirteen hats had a full set of mask frames sitting on disk with `clipsHair`
switched OFF, so the clip was never applied. But turning the flag on was not
enough: those masks were generated by the OLD diff-based importer, from the
OLD art -- the art that had the character's head baked into every frame. A
mask cut from a hat-plus-head silhouette clips the hair to the wrong shape.
The hats have all been re-cut since (v2.3.1502-1523), so the masks are rebuilt
from what is on disk today.

The mask
--------
Two parts, and the second one is v2.3.1529 (owner):

  1. AT AND ABOVE THE HAT, the hair is no wider than the hat is at that row or
     any row above it.
  2. Everywhere BELOW the hat's lowest pixel, full width.

Part 2 is what lets hair show beside a brim. Without it the mask was only ever
as wide as the hat, so a Sombrero or a cowboy hat -- which leave the whole head
below the brim in plain view -- showed no hair at all, which read as the hat
shaving you. Filling below the hat's bottom edge means the brim still cuts
everything that would poke up past it while the hair under and beside it
survives.

Part 1 is v2.3.1957, and it is the owner's own rule, quoted:

    "For the hair mask it's best to clip the width of the hair and any hair
    above it based on the width equal to and above the hat item.  Other
    headwear (like bandana, other open top headwear, etc) would be the
    exceptions to that rule."

It used to say "in a column the hat occupies, everything from the hat's topmost
pixel downward", which bounds the hair vertically and not at all horizontally:
a column stayed open to the bottom of the frame once the hat had touched it, so
an afro under a beanie kept its full un-hatted width and the hat read as
perched on a ball. It also left a vertical CORRIDOR either side of an eared hat
where hair floated in mid-air with nothing under it (measured on mickey-ears:
86px south, 99 southwest, 119 east).

Bounding the width closes both. The bound accumulates DOWNWARD -- the widest
the hat has been at this row or above -- so a dome, whose widest row is its
bottom, is unaffected at its own bottom edge, while an ear stops counting the
moment it ends.

WHAT THIS DELIBERATELY ALLOWS: skin beside the hat where the hair used to
bulge. That is the point. It is also why bald_px below had to be re-aimed --
see the note there.

Run from the repo root:
    python3 tools/make_hairmask.py --all-with-masks [--apply]
    python3 tools/make_hairmask.py --ids beanie,top-hat --apply
    [--set-clips]   also switch clipsHair on (default when --apply)

v2.3.1532: a hat that does not COVER the crown is REFUSED -- see bald_px().
"""
import argparse
import json
import os
import numpy as np
from PIL import Image

DIRS = ['south', 'southwest', 'east', 'northeast', 'north']
HEADWEAR = 'public/sprites/traits/headwear'
BODY = 'public/sprites/player/stand-{dir}.png'
BODY_TOPS = 'public/sprites/player/body-tops.json'
ALPHA_T = 16
FRAME = 256
SKULL_ROWS = 26      # 256-space rows below the crown that count as scalp
BALD_T = 150         # exposed scalp px above which a hat must NOT clip hair


def _load256(p):
    im = Image.open(p).convert('RGBA')
    if im.width != FRAME:
        im = im.resize((FRAME, round(im.height * FRAME / im.width)), Image.NEAREST)
    return np.array(im)


def _place(art, meta, d, tops):
    """Where _placeTrait puts this frame on the standing body, in the 256 frame."""
    a = meta['anchors'][d]
    n = meta.get('crownNudge', {}).get(d, [0, 0])
    sc = meta.get('scale', {}).get(d, 1)
    if sc != 1:
        art = np.array(Image.fromarray(art).resize((max(1, round(FRAME * sc)),) * 2, Image.NEAREST))
        a = [a[0] * sc, a[1] * sc]
        n = [n[0] * sc, n[1] * sc]
    bx, by = tops[f'stand-{d}-0']
    dx, dy = round(bx - (a[0] - n[0])), round(by - (a[1] - n[1]))
    out = np.zeros((FRAME, FRAME, 4), np.uint8)
    hh, hw = art.shape[:2]
    ys, xs = slice(max(0, dy), min(FRAME, hh + dy)), slice(max(0, dx), min(FRAME, hw + dx))
    sy, sx = slice(max(0, -dy), min(hh, FRAME - dy)), slice(max(0, -dx), min(hw, FRAME - dx))
    out[ys, xs] = art[sy, sx]
    return out


def bald_px(hid, meta, masks):
    """Worst-case scalp left bare if this hat clips hair to `masks`.

    v2.3.1532.  A mask cuts hair everywhere it is transparent, so a hat that
    does not COVER the crown shaves it: the Naruto Headband, the Red Bandana
    and the Blue Bandana are bands across the forehead, and clipping to them
    left a bare skin dome above the band (owner report, all three measured
    380-603px against 65px for the worst real cap).  Refuse to switch the flag
    on for that shape rather than trust "it has a mask folder, so it must
    cover the skull".
    """
    if not os.path.isfile(BODY_TOPS):
        return 0, ''       # can't judge without the crown table; don't block
    tops = json.load(open(BODY_TOPS))
    worst, worst_d = 0, ''
    for d, mask in masks.items():
        if d not in meta.get('anchors', {}):
            continue
        hat = _place(_load256(f'{HEADWEAR}/{hid}/{d}.png'), meta, d, tops)
        # the mask is built at the ART's native size (128 since v2.3.1526); the
        # hat and body here are in the 256 frame the meta is expressed in, so it
        # has to come up to 256 too or it lands at half size and reads as bald
        if mask.shape[0] != FRAME:
            mask = np.array(Image.fromarray(mask).resize((FRAME, FRAME), Image.NEAREST))
        msk = _place(mask, meta, d, tops)
        body = _load256(BODY.format(dir=d))
        by = tops[f'stand-{d}-0'][1]
        skull = body[:, :, 3] > ALPHA_T
        skull[:by, :] = False
        skull[by + SKULL_ROWS:, :] = False
        # v2.3.1957: only UNDER THE HAT.  The width rule intentionally leaves
        # skin beside a cap -- that is the hair being pressed down rather than
        # ballooning -- so counting it made the guard refuse 21 of 31 real
        # caps.  What the guard is actually for is the shape it was written
        # against: a BAND, which leaves the whole dome above it bare.  That
        # dome is inside the band's own columns, so scoping the count to the
        # hat's horizontal span keeps every band refused and stops punishing
        # caps for doing the thing the owner asked for.
        span = np.zeros(FRAME, bool)
        hcols = np.nonzero((hat[:, :, 3] > ALPHA_T).any(axis=0))[0]
        if len(hcols):
            span[hcols.min():hcols.max() + 1] = True
        n = int((skull & span[None, :]
                 & (msk[:, :, 3] <= ALPHA_T) & (hat[:, :, 3] <= ALPHA_T)).sum())
        if n > worst:
            worst, worst_d = n, d
    return worst, worst_d


def build(hid, apply_it, set_clips):
    root = f'{HEADWEAR}/{hid}'
    mp = f'{root}/meta.json'
    if not os.path.isfile(mp):
        raise SystemExit(f'no hat called {hid}')
    meta = json.load(open(mp))
    made = []
    masks = {}
    for d in DIRS:
        p = f'{root}/{d}.png'
        if not os.path.isfile(p):
            continue
        a = np.array(Image.open(p).convert('RGBA'))
        m = a[:, :, 3] > ALPHA_T
        h, w = m.shape
        mask = np.zeros((h, w, 4), np.uint8)
        rows = np.nonzero(m.any(axis=1))[0]
        if len(rows):
            # everything below the hat's lowest pixel, at full width
            mask[rows.max() + 1:, :] = (255, 255, 255, 255)
        # v2.3.1957: at and above the hat, no wider than the hat has been at
        # this row or above it.  `lo`/`hi` accumulate as the scan goes down.
        if len(rows):
            lo, hi_ = w, -1
            for y in range(int(rows.min()), int(rows.max()) + 1):
                r = np.nonzero(m[y, :])[0]
                if len(r):
                    lo = min(lo, int(r.min()))
                    hi_ = max(hi_, int(r.max()))
                if hi_ >= 0:
                    mask[y, lo:hi_ + 1] = (255, 255, 255, 255)
        made.append((d, int(m.sum()), int((mask[:, :, 3] > 0).sum()), w))
        masks[d] = mask
        if apply_it:
            os.makedirs(f'{root}/hairmask', exist_ok=True)
            Image.fromarray(mask).save(f'{root}/hairmask/{d}.png')
    was = bool(meta.get('clipsHair'))
    bald, bald_d = bald_px(hid, meta, masks) if masks else (0, '')
    if bald >= BALD_T:
        set_clips = False
        print(f'  {hid:<20} REFUSING to clip: leaves {bald}px of bare scalp on {bald_d} '
              f'(limit {BALD_T}) -- this is a band, not a cap; clipping would shave the crown')
    if apply_it and set_clips:
        meta['clipsHair'] = True
        meta['note'] = (meta.get('note', '') + ' v2.3.1957: hair-clip mask rebuilt by '
                        'tools/make_hairmask.py under the WIDTH rule (owner: clip the hair to '
                        'the hat\'s width at and above the hat)'
                        + ('' if was else ', and clipsHair switched on') + '.')
        with open(mp, 'w') as fh:
            json.dump(meta, fh, indent=2)
            fh.write('\n')
    sizes = {x[3] for x in made}
    print(f'  {hid:<20} {len(made)} frame(s) at {"/".join(str(s) for s in sizes)}px'
          f'   clipsHair {was} -> {True if (apply_it and set_clips) else was}')
    return len(made)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ids', default=None)
    ap.add_argument('--all-with-masks', action='store_true')
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--set-clips', action='store_true')
    args = ap.parse_args()

    if args.all_with_masks:
        # having a mask folder at all IS the record of which hats were judged to
        # cover the skull; that judgement is kept, only the pixels are redone
        ids = [h for h in sorted(os.listdir(HEADWEAR))
               if os.path.isdir(f'{HEADWEAR}/{h}/hairmask')]
    elif args.ids:
        ids = args.ids.split(',')
    else:
        raise SystemExit('pass --ids or --all-with-masks')

    print(f'{len(ids)} hat(s):')
    n = sum(build(h, args.apply, args.set_clips or args.apply) for h in ids)
    print(f'{n} mask frame(s) {"written" if args.apply else "would be written"}')


if __name__ == '__main__':
    main()
