"""One-shot recolor for the hand-keyed jog-east sheet.

The east sheet was processed by a different (older, hand-tuned)
pipeline, so it ended up visually different from north/south/SW/NE
in three measurable ways:

  1. Skin tone is darker — median (201,130,68) vs (~222,147,78) for
     the others.
  2. Outline color is lighter — median (67,41,33) vs (~38,10,18).
  3. Outline is anti-aliased — 5000+ partial-alpha pixels along the
     silhouette edge, vs 0 in the binary-alpha sheets.

This tool brings east in line with SW (the canonical skin reference):
  - Apply per-channel multiplier to skin pixels so their median
    matches SW's.
  - Snap any opaque dark pixel (lum < 80) to the canonical outline
    color (38,10,18).
  - Force binary alpha (alpha < 128 -> 0, else 255) to match the
    hard-edge silhouette of the other sheets.
  - Re-zero RGB on alpha=0 to prevent halo bleed during scaling.

Run once and check the result in.  Don't add this to
regen_jog_sprites.sh — east is not regenerated by that script.

CLI:
  python tools/recolor_east.py public/sprites/player/jog-east.png \\
      public/sprites/player/jog-east.png
"""
import argparse
from pathlib import Path
from PIL import Image

# Outline target sampled from jog-southwest.png (canonical reference).
OUTLINE_TARGET = (38, 10, 18)

# Skin target: averaged across N/S/SW so east lands in the middle of
# the other three directions, not at SW's brightest extreme.  An
# earlier pass shifted east all the way to SW's (225,148,76) and the
# user said it looked too bright.
SKIN_TARGET = (220, 147, 78)

# Source medians (sampled from the original jog-east.png before any recolor).
SKIN_SRC = (201, 130, 68)


def is_skin(r, g, b, a):
    if a < 240:
        return False
    if not (r > g and g > b):
        return False
    if r < 120:
        return False
    if r > 235 and g > 220 and b > 200:
        return False
    sat = (max(r, g, b) - min(r, g, b)) / max(max(r, g, b), 1)
    return sat >= 0.15


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("src")
    p.add_argument("dst")
    p.add_argument("--alpha-thresh", type=int, default=128,
                   help="alpha threshold for binarization (default 128)")
    p.add_argument("--outline-lum", type=int, default=80,
                   help="lum below which a pixel is considered outline "
                        "(default 80)")
    args = p.parse_args()

    src = Path(args.src)
    dst = Path(args.dst)
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    px = img.load()

    # Per-channel multipliers from east skin median -> SW skin median.
    rm = SKIN_TARGET[0] / SKIN_SRC[0]
    gm = SKIN_TARGET[1] / SKIN_SRC[1]
    bm = SKIN_TARGET[2] / SKIN_SRC[2]

    skin_n = 0
    outline_n = 0
    binarize_n = 0

    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]

            # Step 1: binarize alpha first so we know the silhouette.
            if 0 < a < 255:
                if a >= args.alpha_thresh:
                    a = 255
                else:
                    a = 0
                binarize_n += 1

            if a == 0:
                px[x, y] = (0, 0, 0, 0)
                continue

            lum = (r + g + b) / 3

            # Step 2: snap dark pixels to canonical outline.
            if lum < args.outline_lum:
                px[x, y] = (OUTLINE_TARGET[0], OUTLINE_TARGET[1],
                            OUTLINE_TARGET[2], a)
                outline_n += 1
                continue

            # Step 3: shift skin pixels toward SW skin tone.
            if is_skin(r, g, b, a):
                nr = min(255, max(0, round(r * rm)))
                ng = min(255, max(0, round(g * gm)))
                nb = min(255, max(0, round(b * bm)))
                px[x, y] = (nr, ng, nb, a)
                skin_n += 1
                continue

            # Other pixels (pants, eyes, anything between skin/outline) —
            # leave alpha-binarized but keep RGB.
            px[x, y] = (r, g, b, a)

    img.save(dst, "PNG", optimize=True)
    print(f"{src.name} -> {dst.name}: "
          f"binarized {binarize_n} alpha pixels, "
          f"snapped {outline_n} outline pixels to {OUTLINE_TARGET}, "
          f"recolored {skin_n} skin pixels by mul "
          f"({rm:.3f}, {gm:.3f}, {bm:.3f})")


if __name__ == "__main__":
    main()
